name: CI Build & Secure Docker Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build project
      - name: Build project
        run: dotnet build --configuration Release

      # 5. Build Docker image
      - name: Build Docker image
        run: docker build -t securewebapi .

      # 6. Security scanning (Trivy)
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: securewebapi
          format: table
          exit-code: 0
          ignore-unfixed: true

      # 7. Run container with secret (test step)
      - name: Run Docker container
        run: |
          docker run -d -p 5000:8080 \
          -e MY_SECRET=${{ secrets.MY_SECRET }} \
          --name securewebapi securewebapi