name: CI Build & Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build project
      - name: Build project
        run: dotnet build --configuration Release

      # Build Docker image
      - name: Build Docker image
        run: docker build -t securewebapi .

       # Security scan using Trivy
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: securewebapi
          format: table
          exit-code: 0
          ignore-unfixed: true